package painterStudio;

import java.awt.Color;
import java.awt.Point;
import java.util.Timer;
import java.util.TimerTask;

public class PainterStudio extends javax.swing.JFrame {
    
    private int mouseX = 0;
    private int mouseY = 0;
    Timer timer;
    TimerTask timerTask;
    
    

    public PainterStudio() {
        initComponents();
        board.setBackground(Color.white);
        pencilThicknessSlider.setPaintTicks(true);
        pencilThicknessSlider.setPaintLabels(true);
        pencilThicknessSlider.setMinimum(0);
        pencilThicknessSlider.setMaximum(20);
        pencilThicknessSlider.setValue(10);
        pencilThicknessSlider.setMajorTickSpacing(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new painterStudio.Board();
        colorPanel = new javax.swing.JPanel();
        colorBoardLabel = new javax.swing.JLabel();
        colorPencilLabel = new javax.swing.JLabel();
        colorBoardComboBox = new javax.swing.JComboBox<>();
        colorPencilComboBox = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        thicknessPanel = new javax.swing.JPanel();
        pencilThicknessSlider = new javax.swing.JSlider();
        thicknessPencilLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        board.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        board.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                boardMouseMoved(evt);
            }
        });
        board.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        colorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));

        colorBoardLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        colorBoardLabel.setText("Pizarra:");

        colorPencilLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        colorPencilLabel.setText("Lápiz:");

        colorBoardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo", "Azul" }));
        colorBoardComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorBoardComboBoxActionPerformed(evt);
            }
        });

        colorPencilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo", "Azul" }));
        colorPencilComboBox.setSelectedIndex(1);
        colorPencilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorPencilComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorPanelLayout.createSequentialGroup()
                        .addComponent(colorBoardLabel)
                        .addGap(18, 18, 18)
                        .addComponent(colorBoardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanelLayout.createSequentialGroup()
                        .addComponent(colorPencilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorPencilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorBoardLabel)
                    .addComponent(colorBoardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorPencilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPencilLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("ESTELA DEL RATÓN - PAINTER STUDIO");

        thicknessPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Grosor"));

        pencilThicknessSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pencilThicknessSliderStateChanged(evt);
            }
        });

        thicknessPencilLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        thicknessPencilLabel.setText("Lápiz:");

        javax.swing.GroupLayout thicknessPanelLayout = new javax.swing.GroupLayout(thicknessPanel);
        thicknessPanel.setLayout(thicknessPanelLayout);
        thicknessPanelLayout.setHorizontalGroup(
            thicknessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thicknessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thicknessPencilLabel)
                .addGap(18, 18, 18)
                .addComponent(pencilThicknessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thicknessPanelLayout.setVerticalGroup(
            thicknessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thicknessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thicknessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencilThicknessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thicknessPencilLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        authorsLabel.setText("Raúl Lozano Ponce, Pablo Perdomo Falcón");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(board, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(thicknessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(authorsLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thicknessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseEntered
        timer = new Timer();
        timerTask = new TimerTask() {
            @Override
            public void run() {
                board.paintInBoard(new Point(mouseX, mouseY));
                repaint();
            }
        };
        timer.schedule(timerTask,0,100);
    }//GEN-LAST:event_boardMouseEntered

    private void boardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseMoved
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_boardMouseMoved

    private void boardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMouseExited
        timer.cancel();
        board.deleteCircles();
        repaint();
    }//GEN-LAST:event_boardMouseExited

    private void colorBoardComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorBoardComboBoxActionPerformed
        board.changeBoardColor((String) colorBoardComboBox.getSelectedItem());
    }//GEN-LAST:event_colorBoardComboBoxActionPerformed

    private void colorPencilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorPencilComboBoxActionPerformed
        board.changePencilColor((String) colorPencilComboBox.getSelectedItem());
    }//GEN-LAST:event_colorPencilComboBoxActionPerformed

    private void pencilThicknessSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pencilThicknessSliderStateChanged
        board.changePencilThickness(pencilThicknessSlider.getValue());
    }//GEN-LAST:event_pencilThicknessSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainterStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainterStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainterStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainterStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainterStudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private painterStudio.Board board;
    private javax.swing.JComboBox<String> colorBoardComboBox;
    private javax.swing.JLabel colorBoardLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JComboBox<String> colorPencilComboBox;
    private javax.swing.JLabel colorPencilLabel;
    private javax.swing.JSlider pencilThicknessSlider;
    private javax.swing.JPanel thicknessPanel;
    private javax.swing.JLabel thicknessPencilLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
